### PR TITLE
Allow using the query param `sslmode=require` to enable SSL

### PR DESCRIPTION
**Pull request by seanCodes**
In Heroku's postgres docs, the query param `sslmode=require` is [called](https://devcenter.heroku.com/articles/heroku-postgresql#heroku-postgres-ssl) [out](https://devcenter.heroku.com/articles/heroku-postgresql#remote-connections) [several](https://devcenter.heroku.com/articles/heroku-postgresql#external-connections-ingress) [times](https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku#ssl) as the solution for enabling SSL when connecting to a postgres DB. Since using this plugin with Heroku seems like a common use case, it makes sense to support that query param as an alternative to the current `ssl=true` param for enabling SSL.

### CODE REVIEW

**Comment by jmeas** [comment]
Thanks for the PR, @seanCodes !

I think it's worth considering adding something like this to the lib, but it would require updating node-postgres upstream.

As an to answer your specific concern about using Postgres on Heroku, Postgres translates `ssl=true` into `sslmode=require` under-the-hood ([source: search this page for ssl=true](https://www.postgresql.org/docs/9.6/static/libpq-connect.html)), so they're functionally the same.

If we do wish to add this other param, we'd likely also want to support the values `verify-ca` and `verify-full` ([source](https://www.postgresql.org/docs/9.6/static/libpq-ssl.html)). However, node-postgres doesn't support this in query param form ([source1](https://github.com/brianc/node-postgres/issues/643#issuecomment-55911493) / [source2](https://github.com/iceddev/pg-connection-string/blob/45d82320b7f5a11f622789f5a21d3e0df96ab8da/index.js#L50)).

It'd be strange if we only supported `sslmode=require` without the other options. And if we support the other options, then we'd want to pass them straight through.

Do you think this is worth upstreaming @daliwali / @seanCodes ? If so, we should move the conversation there, then revisit once node-postgres is updated.

Thanks again for the PR, @seanCodes :v:

**Comment by seanCodes** [comment]
@jmeas Ah, that makes sense. Maybe a better solution would be just to document the `ssl=true` method of enabling SSL in the README, then. That way the option can stay agnostic.

Happy to update the PR if that sounds like a better move :thumbsup:

**Comment by jmeas** [comment]
@seanCodes , the situation is kind of tough. Whenever one option is just fed to some other lib, I prefer to say: "Refer to that other lib's documentation for how to configure it," with a link (similar to how the connection object links out to pg-pool).

This is economical, so that we're not double-documenting another lib's API, and also beneficial to the user since the other lib's docs will cross-reference itself, etc.

In this situation, though, node-postgres [is pretty light on the URL documentation](https://github.com/brianc/node-postgres/wiki/Client#new-clientstring-url-client), and it kinda seems like they have a strong preference for the obj config. Somewhere in their docs forward you to their URL parser, which is [pg-connection-string](https://github.com/iceddev/pg-connection-string), but the docs there are nonexistent.

Anyway, because of all of this, you may be right that it'd be best for us to leave a note here. Want to modify this PR in a way that you think helps clarify things?

Thanks again for these suggestions to make this lib better! :v:

**Comment by daliwali** [comment]
I agree that this might be better if it were handled upstream.

One thing that is not clear to me is whether `sslmode=require` is vendor-specific to Heroku, or is this just a Postgres thing?

**Comment by jmeas** [comment]
@daliwali it’s not vendor-specific to Heroku, it’s a postgres thing (I linked to the docs in an earlier post). If it were just a Heroku thing I’d be more hesitant about supporting it here :)

**Comment by seanCodes** [comment]
@jmeas @daliwali I've gone ahead and removed the code to support `sslmode=require` and documented `ssl=true` in the readme. Let me know if you want any changes made!

**Comment by jmeas** [comment]
Thanks for the update, @seanCodes ! This looks good to me. What do you think, @daliwali ?

**Comment by daliwali** [comment]
Looks good to me. I've added @jmeas to publish it on npm whenever.

**Comment by jmeas** [comment]
:tada: thanks @daliwali ! This is just a README change, so we won't need a publish.

Thanks again for the PR, @seanCodes !

**Pull request merged**
